### ISSUE TITLE
Need help with dashboard integration

### ISSUE THREAD

**Issue by Mahonzu** [adryd325/sneaky#11]
Hello! Thank you for making this amazing project! I need help making it work with my server dashboard, I am using [homepage](https://gethomepage.dev) It has [minecraft widget](https://gethomepage.dev/latest/widgets/services/minecraft/) and i assume it uses the same protocol as minecraft to get online players and version.  It doesn't work with Sneaky server. I tried adding `127.0.0.1,0` into `allowed-ping-ips.csv`, but it still shows default data (0/20 players). Both the homepage and the minecraft server are docker containers. Can I check which IP is requesting server info?

**Comment by adryd325** [comment]
could you run `ip addr` inside the widget's docker container?

**Comment by Mahonzu** [comment]
Sure. here's the output:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
61: eth0@if62: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.2/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```
I tried adding 172.18.0.2 into allowed ips but it didn't work

**Comment by adryd325** [comment]
Adding 172.18.0.2 would've been my guess. I really need to look into docker's networking a bit more.

I could compile a custom version of the mod that logs every ping if that'd help

**Comment by Mahonzu** [comment]
> I could compile a custom version of the mod that logs every ping if that'd help

Would be very nice. 1.20.1 fabric, please. Thank you

**Comment by adryd325** [comment]
[sneaky-mc1.21-1.0.13+SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16312669/sneaky-mc1.21-1.0.13%2BSNAPSHOT.jar.zip)

**Comment by Mahonzu** [comment]
Finally found an address. Thank you for taking your time to help me.
Is it possible to add this as an option to config and make it disabled by default? Maybe there's gonna be someone like me. It's fine if you won't. 
Only wish I had money to sponsor your project.

**Comment by adryd325** [comment]
I probably will eventually add a super verbose mode. I have a special branch for tracking server scanners that posts IPs to a Discord webhook (https://github.com/adryd325/sneaky/tree/honeypot) but logging to console is definitely a useful feature.
